name: shell commands 

on:
  - push

#env:
#   aws-access-key-id: ${{ secrets.ACCESS_KEY }}
#   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.4.0
        with:
          terraform_version: 1.4.0
      - name: Terraform init
        run: terraform init   
      - name: Terraform validate
        run: terraform validate
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
      - name: Terraform plan
        run: terraform plan
      - name: release
        run: sudo npx semantic-release
        env: 
          GITHUB_TOKEN: ${{secrets.ELSHUB_TOKEN}}
#      - name: Terraform apply 
#        run: terraform apply -auto-approve
#      - name: Terraform destroy
#        run: terraform destroy -auto-approve  